name: PR

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore solution
        run: dotnet restore

      - name: Install node_modules
        run: bun install --frozen-lockfile

      - name: TypeScript check
        run: bun run lint

      - name: Build daemon
        run : bun run postinstall

      - name: Build sample
        run: bun i && bun run build 2>&1 | grep -i "error" && exit 1 || true
        working-directory: ./sample-project

      - name: Build docs
        run: dotnet fsdocs build --noapidocs --projects "$(pwd)/Fable.Daemon/Fable.Daemon.fsproj"
